/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

module counter(clk, rstn, out);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  input clk;
  output [3:0] out;
  input rstn;
  sky130_fd_sc_hd__o21ai_0 _22_ (
    .A1(_17_),
    .A2(_18_),
    .B1(_21_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__a21oi_1 _23_ (
    .A1(_17_),
    .A2(_18_),
    .B1(_12_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand3_1 _24_ (
    .A(_17_),
    .B(_18_),
    .C(_19_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__a21oi_1 _25_ (
    .A1(_17_),
    .A2(_18_),
    .B1(_19_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__and3b_1 _26_ (
    .A_N(_14_),
    .B(_21_),
    .C(_13_),
    .X(_10_)
  );
  sky130_fd_sc_hd__a31o_1 _27_ (
    .A1(_17_),
    .A2(_18_),
    .A3(_19_),
    .B1(_20_),
    .X(_15_)
  );
  sky130_fd_sc_hd__nand4_1 _28_ (
    .A(_17_),
    .B(_18_),
    .C(_19_),
    .D(_20_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__and3_1 _29_ (
    .A(_21_),
    .B(_15_),
    .C(_16_),
    .X(_11_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _30_ (
    .A(_21_),
    .SLEEP(_17_),
    .X(_08_)
  );
  sky130_fd_sc_hd__dfxtp_1 _31_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _32_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _33_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _34_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(out[3])
  );
  assign _21_ = rstn;
  assign _17_ = out[0];
  assign _18_ = out[1];
  assign _00_[1] = _09_;
  assign _19_ = out[2];
  assign _00_[2] = _10_;
  assign _20_ = out[3];
  assign _00_[3] = _11_;
  assign _00_[0] = _08_;
endmodule
