/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

module decoder2to4(a0, a1, d0, d1, d2, d3);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  input a0;
  input a1;
  output d0;
  output d1;
  output d2;
  output d3;
  sky130_fd_sc_hd__nor2_1 _6_ (
    .A(_0_),
    .B(_1_),
    .Y(_2_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _7_ (
    .A(_0_),
    .SLEEP(_1_),
    .X(_3_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _8_ (
    .A(_1_),
    .SLEEP(_0_),
    .X(_4_)
  );
  sky130_fd_sc_hd__and2_0 _9_ (
    .A(_0_),
    .B(_1_),
    .X(_5_)
  );
  assign _0_ = a0;
  assign _1_ = a1;
  assign d0 = _2_;
  assign d1 = _3_;
  assign d2 = _4_;
  assign d3 = _5_;
endmodule
